apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: next-app-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
  params:
    - name: source-repo
      type: string
      description: Source code repository
    - name: image-repo
      type: string
      description: Quay image repository
    - name: app-name
      type: string
      description: Application name
  tasks:
    - name: git-clone-repo
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.source-repo)"
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: npm-install-run-test
      runAfter:
        - git-clone-repo
      taskRef:
        kind: Task
        name: npm
      params:
        - name: ARGS
          value:
            - install-ci
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: build-and-push-image
      runAfter:
        - npm-install-run-test
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.git-clone-repo.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: create-envorinment-config
      runAfter:
        - build-and-push-image
      taskRef:
        name: kustomize
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
        - name: source-repo
          value: "$(params.source-repo)"
        - name: commit
          value: "$(tasks.git-clone-repo.results.commit)"
        - name: image-repo
          value: "$(params.image-repo)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: try-to-deploy
      runAfter:
        - create-envorinment-config
      taskRef:
        name: try-to-deploy
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
